# Generated by Django 5.0.6 on 2024-07-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=100)),
                ('teacher_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('pan_card', models.CharField(max_length=100)),
                ('aadhar_card', models.CharField(max_length=100)),
                ('mobile_number', models.IntegerField(blank=True, default=0)),
                ('alter_number', models.IntegerField(blank=True, default=0)),
                ('date_of_birth', models.CharField(max_length=100)),
                ('previous_school_name', models.CharField(max_length=250)),
                ('transport_fees', models.IntegerField(blank=True, default=0)),
                ('graduation_complete', models.BooleanField(default=False)),
                ('bed_complete', models.BooleanField(default=False)),
                ('created_by', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
