# Generated by Django 5.0.6 on 2024-08-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=100)),
                ('teacher_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('pan_card', models.CharField(max_length=100)),
                ('aadhar_card', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=100)),
                ('alter_number', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('previous_school_name', models.CharField(max_length=250)),
                ('transport_fees', models.CharField(max_length=100)),
                ('graduation_complete', models.BooleanField(default=False)),
                ('bed_complete', models.BooleanField(default=False)),
                ('created_by', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.CharField(unique=True)),
                ('company', models.CharField(max_length=100)),
                ('terms_and_condition', models.BooleanField()),
                ('role', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
