# Generated by Django 5.0.6 on 2024-07-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherdetails',
            name='salary',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='teacherdetails',
            name='subject',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
