# Generated by Django 5.0.6 on 2024-07-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_teacherdetails_salary_teacherdetails_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherdetails',
            name='alter_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teacherdetails',
            name='mobile_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teacherdetails',
            name='salary',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teacherdetails',
            name='transport_fees',
            field=models.CharField(max_length=100),
        ),
    ]
