# Generated by Django 5.0.6 on 2024-07-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_teacherdetails_alter_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherdetails',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
